<?php

/**
 * ProjectsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Projects');
    }
    
    public static function getOne($project_id) {
        return Doctrine_Query::create()
                        ->select('p.*, pi.*')
                        ->from('Projects p, p.ProjectImages pi')
                        ->where('p.id =?', $project_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getActiveProjects($limit = FALSE) {
        $q = Doctrine_Query::create()
                ->select('p.*')
                ->from('Projects p')
                ->where('p.deleted =?', FALSE);
        if ($limit) {
            $q = $q->limit($limit);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('p.created_at DESC')
                ->execute();

        return $q;
    }
    
    public static function getRandOne() {
        return Doctrine_Query::create()
                ->select('p.*')
                ->from('Projects p')
                ->where('p.deleted=0')
                ->setHydrationMode(Doctrine::HYDRATE_SCALAR)
                ->orderBy('RAND()')
                ->limit(1)
                ->fetchOne();
    }
}