<?php

/**
 * ServicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Services');
    }
    
    public static function getOne($service_id) {
        return Doctrine_Query::create()
                        ->select('s.*')
                        ->from('Services s')
                        ->where('s.id =?', $service_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getActiveServices($limit = FALSE) {
        $q = Doctrine_Query::create()
                ->select('s.*')
                ->from('Services s')
                ->where('s.deleted =?', FALSE);
        if ($limit) {
            $q = $q->limit($limit);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('s.created_at DESC')
                ->execute();

        return $q;
    }
    
    public static function getRandOne() {
        return Doctrine_Query::create()
                ->select('s.*')
                ->from('Services s')
                ->where('s.deleted=0')
                ->setHydrationMode(Doctrine::HYDRATE_SCALAR)
                ->orderBy('RAND()')
                ->limit(1)
                ->fetchOne();
    }
   
}