<?php

/**
 * Services
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Services extends BaseServices
{
    public function addService(array $data) {
        $errors = $this->__validateService($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $s = new Services();
            $s->title = $data['title'];
            $s->description = $data['description'];
            $s->image = $errors['image'];
            $s->created_at = date('ymdHis');
            $s->save();

            return $errors;
        }
    }

    public function updateService(array $data) {
        $errors = $this->__validateService($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            Doctrine_Query::create()
                    ->update('Services s')
                    ->set('s.title', '?', $data['title'])
                    ->set('s.description', '?', $data['description'])
                    ->set('s.image', '?', $errors['image'])
                    ->set('s.updated_at', '?', date('ymdHis'))
                    ->where('s.id =?', $data['id'])
                    ->execute();

            return $errors;
        }
    }

    public function deleteService($service_id) {
        Doctrine_Query::create()
                ->update('Services s')
                ->set('s.deleted', '?', TRUE)
                ->where('s.id =?', $service_id)
                ->execute();
    }

    private function __validateService($data) {
        $errors = array();
        $error_flag = false;

        if (!required($data['title'])) {
            $errors['title'] = 'Please write in event title';
            $error_flag = true;
        }
        if (!required($data['description'])) {
            $errors['description'] = 'Please write in service description';
            $error_flag = true;
        }

        if (isset($data['id'])) {
            if (isset($_FILES['userfile']) && !empty($_FILES['userfile']['name'])) {
                $upload_data = upload_file('services', array('jpg|png|jpeg|gif'), '2028');
                if ($upload_data['error_flag']) {
                    $errors['image'] = $upload_data['errors'];
                    $error_flag = true;
                } else {
                    $errors['image'] = $upload_data['upload_data']['file_name'];
                }
            } else if ($data['image']) {
                $errors['image'] = $data['image'];
            }
        } else {
            $upload_data = upload_file('services', array('jpg|png|jpeg|gif'), '2028');
            if ($upload_data['error_flag']) {
                $errors['image'] = $upload_data['errors'];
                $error_flag = true;
            } else {
                $errors['image'] = $upload_data['upload_data']['file_name'];
            }
        }

        
        $errors['error_flag'] = $error_flag;

        return $errors;
    }
}