<?php

/**
 * StaticPages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StaticPages extends BaseStaticPages
{
    public function updateStaticPage($data){
        Doctrine_Query::create()
                ->update('StaticPages sp')
                ->set('sp.description', '?', $data['description'])
                ->set('sp.updated_at', '?', date('ymdHis'))
                ->where('sp.page_id =?', $data['page_id'])
                ->execute();
    }
}